# Generated by Django 6.0.3 on 2026-03-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
                ('data', models.DateField()),
                ('hora', models.TimeField()),
                ('pessoas', models.PositiveIntegerField()),
                ('observacoes', models.TextField()),
            ],
        ),
    ]
