# Generated by Django 6.0.3 on 2026-03-03 22:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0002_reserva'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='nome',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='reserva',
            old_name='nome',
            new_name='name',
        ),
    ]
