# Generated by Django 6.0.3 on 2026-03-04 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0003_rename_nome_menu_name_rename_nome_reserva_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reserva',
            name='observacoes',
            field=models.TextField(default='Nenhuma'),
        ),
    ]
