# Generated by Django 6.0.3 on 2026-03-05 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0004_alter_reserva_observacoes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='descricao',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='menu',
            name='imagem',
            field=models.ImageField(null=True, upload_to='img'),
        ),
    ]
