# Generated by Django 6.0.3 on 2026-03-05 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0005_alter_menu_descricao_alter_menu_imagem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menu',
            name='imagem',
        ),
    ]
