# Generated by Django 6.0.3 on 2026-03-05 13:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0006_remove_menu_imagem'),
    ]

    operations = [
        migrations.RenameField(
            model_name='menu',
            old_name='name',
            new_name='nome',
        ),
    ]
