# Generated by Django 6.0.3 on 2026-03-05 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_restaurant', '0007_rename_name_menu_nome'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menu',
            name='descricao',
            field=models.TextField(default='Nenhuma'),
        ),
    ]
